name: Test, build and push operator

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make lint
      - run: make test

  build-amd64:
    needs: [ test ]
    runs-on: debian-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Login to container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: arch
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: git.gmem.ca
      - name: Login to ghcr.io
        uses: https://github.com/docker/login-action@v3
        with:
          username: gmemstr
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          tags: git.gmem.ca/arch/warrior-operator:amd64,ghcr.io/gmemstr/warrior-operator:amd64

  build-arm64:
    needs: [ test ]
    runs-on: debian-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Login to container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: arch
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: git.gmem.ca
      - name: Login to ghcr.io
        uses: https://github.com/docker/login-action@v3
        with:
          username: gmemstr
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          tags: git.gmem.ca/arch/warrior-operator:arm64,ghcr.io/gmemstr/warrior-operator:arm64

  merge:
    runs-on: debian-latest
    needs: [ build-amd64, build-arm64 ]
    steps:
      - name: Login to container registry
        uses: https://github.com/docker/login-action@v3
        with:
          username: arch
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: git.gmem.ca
      - name: Login to ghcr.io
        uses: https://github.com/docker/login-action@v3
        with:
          username: gmemstr
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
          registry: ghcr.io
      - name: Merge and push manifest
        run: |
          echo "Merging and pushing to Forgejo"
          docker manifest create git.gmem.ca/arch/warrior-operator:latest \
            --amend git.gmem.ca/arch/warrior-operator:amd64 \
            --amend git.gmem.ca/arch/warrior-operator:arm64
          docker manifest push git.gmem.ca/arch/warrior-operator:latest
          echo "Mirroring to ghcr.io"
          docker manifest create ghcr.io/gmemstr/warrior-operator:latest \
            --amend ghcr.io/gmemstr/warrior-operator:amd64 \
            --amend ghcr.io/gmemstr/warrior-operator:arm64
          docker manifest push ghcr.io/gmemstr/warrior-operator:latest
