on:
  push:

jobs:
  test:
    runs-on: debian-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - run: make lint
    - run: make test
